export const ORDER = "MAKE_ORDER";
export const RESET_SELECTED_PRODUCT = "RESET_SELECTED_PRODUCT";
export const RETURN_COINS_TO_USER = "RETURN_COINS";
export const CALCULATE_CHANGE = "CALCULATE_CHANGE";
export const ADD_COINS = "MACHINE_ADD_COINS";
export const TOGGLE_KEYBOARD = "TOGGLE_KEYBOARD";
